name: ocr
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - altgraph=0.17
  - bzip2=1.0.8
  - ca-certificates=2022.2.1
  - certifi=2021.10.8
  - cffi=1.15.0
  - click=8.0.4
  - colorama=0.4.4
  - dataclasses=0.8
  - flask=2.0.2
  - flask_cors=3.0.10
  - freeglut=3.2.2
  - freetype=2.10.4
  - future=0.18.2
  - gevent=21.8.0
  - gevent-websocket=0.10.1
  - greenlet=1.1.1
  - icu=68.2
  - intel-openmp=2022.0.0
  - itsdangerous=2.0.1
  - jasper=2.0.33
  - jbig=2.1
  - jinja2=3.0.2
  - jpeg=9e
  - lcms2=2.12
  - leptonica=1.78.0
  - lerc=3.0
  - libarchive=3.5.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libdeflate=1.10
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopencv=4.5.5
  - libpng=1.6.37
  - libprotobuf=3.19.4
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.12
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - lzo=2.10
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - macholib=1.14
  - markupsafe=2.0.1
  - mkl=2022.0.0
  - msys2-conda-epoch=20160418
  - numpy=1.22.2
  - opencv=4.5.5
  - openjpeg=2.4.0
  - openssl=1.1.1m
  - packaging=21.3
  - pandas=1.2.4
  - pefile=2019.4.18
  - pillow=9.0.1
  - pip=21.2.4
  - pthread-stubs=0.4
  - py-opencv=4.5.5
  - pycparser=2.21
  - pycryptodome=3.12.0
  - pyinstaller=4.8
  - pyparsing=3.0.7
  - pytesseract=0.3.9
  - python=3.9.7
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2021.3
  - pywin32=302
  - pywin32-ctypes=0.2.0
  - qt=5.12.9
  - setuptools=58.0.4
  - six=1.15.0
  - sqlite=3.37.2
  - tbb=2021.5.0
  - tesseract=4.1.1
  - tk=8.6.12
  - tzdata=2021e
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - werkzeug=2.0.3
  - wheel=0.37.1
  - whichcraft=0.6.1
  - wincertstore=0.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.11
  - zope=1.0
  - zope.event=4.5.0
  - zope.interface=5.4.0
  - zstd=1.5.2